package models.card.spell;

public enum DefiniteType {
	HOLY_BUFF,
	POWER_AP_BUFF,
	POWER_HP_BUFF,
	POISON_BUFF,
	WEAKNESS_AP_BUFF,
	WEAKNESS_HP_BUFF,
	STUN_BUFF,
	DISARM_BUFF,
	POISON_CELL_EFFECT,
	FIERY_CELL_EFFECT,
	HOLY_CELL_EFFECT,
	REMOVE_BUFF_CARD_EFFECT,
	ADD_AP_CARD_EFFECT,
	ADD_HP_CARD_EFFECT,
	DELETE_AP_CARD_EFFECT,
	DELETE_HP_CARD_EFFECT,
	SACRIFICE_CARD_EFFECT,
	NO_DISARM,
	NO_POISON,
	NO_BAD_EFFECT,
	NO_ATTACK_FROM_WEAKENERS,
	ADD_MANNA,
	ADD_ATTACK_RANGE
}