package client.models.card.spell;

public enum TargetType {
	CELL,
	MY_TROOPS,
	ENEMY_TROOPS,
	ALL_TROOPS,
	MY_HERO,
	ENEMY_HERO,
	ALL_MINION,
	MY_MINION,
	ENEMY_MINION,
	MY_RANGED_HYBRID_HERO,
	OPP_RANGED_HYBRID_HERO,
	RANGED_HYBRID_TROOP
}