package models.message;

public enum MessageType {
    SEND_ERROR, ACCOUNT_COPY, GAME_COPY, SHOP_COPY, CUSTOMDECKS_COPY, LEADERBOARD_COPY, STORIES_COPY, POSITIONS_COPY,
    TO_MAP, TO_HAND, TO_NEXT, TO_COLLECTEDS, TO_GRAVEYARD, MOVE_TROOP, TROOP_AP, TROOP_HP, GET_SHOP, GET_LEADERBOARD,
    SAVE_CHANGES, CREATE_DECK, REMOVE_DECK, ADD_TO_DECK, REMOVE_FROM_DECK, SELECT_DECK, BUY_CARD, SELL_CARD, INSERT,
    ATTACK, COMBO, USE_SPELL, END_TURN, LOG_IN, LOG_OUT,
    CREATE_ACCOUNT,LOGIN,SHOW_LEADER_BOARD,SAVE,LOGOUT,HELP}