package models.message;

public enum  MessageType {
    ACCOUNT, GAME, SHOP, CUSTOMDECKS, LEADERBOARD, STORIES, POSITIONS, INSERT_TROOP, TO_GRAVEYARD, TROOP_AP, TROOP_HP
    , SYS_INSERT, SYS_ATTACK
}