package models.message;

public enum MessageType {
    ACCOUNT_COPY, GAME_COPY, SHOP_COPY, CUSTOMDECKS_COPY, LEADERBOARD_COPY, STORIES_COPY, POSITIONS_COPY, TO_MAP,
    TO_HAND, TO_GRAVEYARD, TROOP_AP, TROOP_HP, SYS_INSERT, SYS_ATTACK, LOG_IN, LOG_OUT
}